version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    env_file:
      - ./.env-docker
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  frontend:
    build:
      context: ./frontend
      target: production-stage
      args:
        - VITE_API_ENDPOINT="http://corpy_backend:8000"
    container_name: corpy_frontend
    env_file:
      - ./.env-docker
    ports:
      - 80:80
  backend:
    build:
      context: ./backend
      args:
        - SECRET_KEY=tUe0v9b-rHFFt7KYMZNFeBS6FDMj9tmRuNH018pJBrg=
        - DATABASE_URL="mysql://root:CorpyCorpy@db:3306/corpy_test"
        - DB_HOST="db"
        - DB_USER="root"
        - DB_PASSWORD="CorpyCorpy"
        - DB_PORT=3306
        - DB_NAME=corpy_test
    ports:
      - 8000:8000
    container_name: corpy_backend
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./.env-docker
    depends_on:
      - db

volumes:
  db_data:
