version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ./.env-docker
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  frontend:
    build:
      context: .
    container_name: corpy_frontend
    env_file:
      - ./.env-docker
    ports:
      - "${FE_PORT}:${FE_PORT}"
  backend:
    build:
      context: .
      args:
        - SECRET_KEY=${SECRET_KEY}
        - DATABASE_URL=${DATABASE_URL}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - CORPY_FRONTEND=${CORPY_FRONTEND}
    ports:
      - "${BE_PORT}:${BE_PORT}"
    container_name: corpy_backend
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port ${BE_PORT}
    env_file:
      - ./.env-docker
    depends_on:
      - db

volumes:
  db_data:
