# Step 1: Build the app using a node image
FROM node:20.18.1 AS build

RUN mkdir app
WORKDIR /app

# Install dependencies and build the project
COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend .
RUN npm run build

# Step 2: Serve the app using a lightweight Nginx image
FROM nginx:alpine

# Copy the custom Nginx configuration
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf

# Copy the built files from the build stage to the Nginx container
COPY --from=build /app/dist /usr/share/nginx/html

# Expose the port that Nginx will serve on
EXPOSE 80

# Start Nginx to serve the app
CMD ["nginx", "-g", "daemon off;"]
