# build stage
FROM node:20.18.1

RUN mkdir app
WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend .
RUN npm run build

RUN ls -l node_modules/.bin

CMD ["npm", "run", "preview"]